package Problems;

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 * <p>
 * EN: https://projecteuler.net/problem=2
 * RU: http://euler.jakumo.org/problems/view/2.html
 */


public class Problem_2 implements IProblem {
    public static final int MAX_FIBONACCI = 4000000;

    public String answer() {
        int i = 0;
        int sum = 0;
        while (fibonachi(i) <= MAX_FIBONACCI) {
            i++;
            if (fibonachi(i) % 2 != 0)
                continue;
            sum += fibonachi(i);
        }

//        System.out.println("Problem 2: " + sum);
        return String.valueOf(sum);
    }

    static int fibonachi(int n) {

        if (n == 0) {
            return 0;
        }
        if (n == 1) {
            return 1;
        }
        return fibonachi(n - 1) + fibonachi(n - 2);

    }
}
